//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

struct DayAvailableResponse: Codable {

    public var date: Date?

    /** Is there an available date */
    public var dayAvailable: Bool?
}
