//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

struct InstructorIntervalRequest: Codable {

    /** Start of time */
    public var beginOfTime: String

    /** End of time */
    public var endOfTime: String
}
