//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

struct PageResponseUserCalendarEventPartnerResponse: Codable {

    /** Elements of the page */
    public var elements: [UserCalendarEventPartnerResponse]?

    /** Current page (starts at 0) */
    public var page: Int?

    /** Page size */
    public var size: Int?

    /** Total elements count */
    public var totalElements: Int?
}
