//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

struct UserDetailsResponse: Codable {

    /** The user's accreditation */
    public var accreditation: String?

    /** Whether the user's organization has an active TUUDR subscription */
    public var activeSubscription: Bool?

    /** The user's affiliation */
    public var affiliation: String?

    /** The user's home country code */
    public var countryCode: String?

    /** The user's display name */
    public var displayName: String?

    /** The user's email address */
    public var email: String?

    /** The user's first name */
    public var firstName: String?

    /** The user's id */
    public var id: Int?

    /** The user's introduction */
    public var introduction: String?

    /** The user's selected language's code */
    public var languageCodes: [String]?

    /** The user's last name */
    public var lastName: String?

    /** The user is searchable in marketplace */
    public var mpSearchEnabled: Bool?

    /** The user's profile picture uuid */
    public var pictureUuid: String?

    /** The user's pronouns */
    public var pronouns: String?

    /** The user's preferred timezone */
    public var timeZone: String?

    /** The user's title */
    public var title: String?

    /** The user's uuid */
    public var userUuid: String?
}
